[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['cd tutora-admin-portal && npm ci']

[phases.build]
cmds = ['cd tutora-admin-portal && npm run build']

[start]
cmd = 'cd tutora-admin-portal && npm start'
