name: tutora
description: A training platform for small businesses
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Supabase packages (Active backend)
  supabase_flutter: ^2.0.0
  provider: ^6.0.5
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  flutter_animate: ^4.2.0
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/ 

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tutora_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true 